# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tweet',
            field=models.ManyToManyField(blank=True, to='twitter.Tweet'),
        ),
    ]
